import CircleLoader from '../../../../../loader/circleLoader/CircleLoader';
import { currencyMinorUnit } from '../../../../../helpers/functions.ts';

import { RTAConfirmationModalPropsType } from './RTAConfirmationModal';

import './initialConfirmationDeleteAccountUI.css';

type InitialConfirmationDeleteAccountUIPropsType =
  RTAConfirmationModalPropsType & {
    buttonDisabled: boolean;
    // Generated by the dialog around this one, which carries the role and so is the
    // element the heading has to name.
    titleId: string;
  };
export const InitialConfirmationDeleteAccountUI = ({
  t,
  affectedAccountsReportCount = 0,
  pocketImpact = [],
  buttonDisabled = false,
  mainStatusFromParent = 'idle',
  onClose,
  onConfirm,
  message = '',
  titleId,
}: InitialConfirmationDeleteAccountUIPropsType) => {
  const showErrorMessage =
    mainStatusFromParent === 'idle' &&
    message &&
    message !== t('clickToConfirm');

  const getConfirmationButtonText = () => {
    return affectedAccountsReportCount === 0
      ? t('confirmHardDelete')
      : t('confirmDeletion');
  };

  return (
    /* No role here: RTAConfirmationModal wraps this and is the dialog, and a dialog nested
       in a dialog is not a structure a screen reader can report. */
    <div className='confirm-delete-container fade-in '>
      <h3 id={titleId} className='confirm-delete-title'>
        {t('title')}
      </h3>

      <p className='confirm-delete-description '>{t('description')}</p>

      <p className='confirm-delete-count '>
        <span className='count-number'>{affectedAccountsReportCount}</span>
        <span className='affected-account'>{t('affectedAccounts')}</span>
      </p>

      {/* Shows which pockets lose backing before confirming: deleting the account removes
          their allocation rows in the same transaction. */}
      {pocketImpact.length > 0 && (
        <div className='pocket-impact-block'>
          <p className='pocket-impact-title'>{t('pocketImpactTitle')}</p>
          <ul className='pocket-impact-list'>
            {pocketImpact.map((row) => (
              <li key={row.pocketId} className='pocket-impact-row'>
                <span className='pocket-impact-name'>{row.pocketName}</span>
                <span className='pocket-impact-amount'>
                  {row.amountAllocated.toFixed(
                    currencyMinorUnit(row.currencyCode),
                  )}{' '}
                  {row.currencyCode}
                </span>
              </li>
            ))}
          </ul>
          <p className='pocket-impact-total'>
            {t('pocketImpactTotalLabel')}{' '}
            {pocketImpact
              .reduce((total, row) => total + row.amountAllocated, 0)
              .toFixed(currencyMinorUnit(pocketImpact[0].currencyCode))}{' '}
            {pocketImpact[0].currencyCode}
          </p>
          <p className='pocket-impact-note'>{t('pocketImpactNote')}</p>
        </div>
      )}

      {buttonDisabled && (
        <div className='processing-indicator' role='status' aria-live='polite'>
          <CircleLoader />
          <p>{message || t('processing')}</p>
        </div>
      )}

      {showErrorMessage && (
        <div className='error-message' role='alert'>
          <strong>{t('apiError')}</strong>
          <span>{'message'} apiError</span>
        </div>
      )}

      <div className={`action-buttons ${buttonDisabled ? 'disabled' : ''}`}>
        <button
          className='cancel-button'
          type='button'
          aria-label={t('cancel')}
          disabled={buttonDisabled}
          onClick={onClose}
        >
          {t('cancel')}
        </button>

        <button
          className='confirm-button'
          type='button'
          disabled={buttonDisabled}
          aria-label={getConfirmationButtonText()}
          onClick={onConfirm}
        >
          {getConfirmationButtonText()}
        </button>
      </div>
    </div>
  );
};

export default InitialConfirmationDeleteAccountUI;
