import { useCallback, useEffect, useRef, useState } from "react";
import { ModalStatusType } from "../../../../types/deletionTypes";
import { DictionaryDataType } from "../../../../utils/languages";

import './statusModalUI.css';

type StatusModalUIPropType={
 modalStatus:ModalStatusType;
 message:string;
 autoCloseDelay?:number;
 showCountdown?:boolean;
 onClose:()=>void;
 onConfirm?:()=>void;
 t:(keyText : keyof DictionaryDataType)=>string;
 // Generated by the wrapping dialog, which carries the role and so is the
 // element the heading has to name.
 titleId:string;
}

export const StatusModalUI = (
 {
  modalStatus,
  message,
  autoCloseDelay=4000,
  onClose,
  onConfirm,
  showCountdown=false,
  t,
  titleId,
}:StatusModalUIPropType) => {
const [timeLeft, setTimeLeft] = useState<number>(Math.floor(autoCloseDelay/1000))

const shouldAutoClose = useRef(false);

useEffect(() => {
 if(modalStatus!=='success' && modalStatus!=='error'){
  return;
 }
 shouldAutoClose.current = false;
  const timerId = setInterval(()=>{
  setTimeLeft((prev)=>{
   if(prev<=1){
    clearInterval(timerId);
    shouldAutoClose.current = true;
    return 0;
   }
    return prev -1
   })
  },1000)

  return () => {
   clearInterval(timerId);
  }
}, [modalStatus, autoCloseDelay])

// Closing is a side effect, so it runs here and not inside the state updater above.
useEffect(() => {
 if (shouldAutoClose.current && (modalStatus === 'success' || modalStatus === 'error')) {
   shouldAutoClose.current = false;
   onClose();
 }
}, [timeLeft, modalStatus, onClose]);

useEffect(() => {
 setTimeLeft(Math.floor(autoCloseDelay / 1000));
}, [modalStatus, autoCloseDelay]);

const handleManualClose = useCallback(
 ()=>{ onClose();},[onClose]
)
const handleConfirm = useCallback(()=>{
 if(onConfirm){
  onConfirm();
 }
}, [onConfirm]
);

 const containerClass = `status-modal-container ${modalStatus}`;

const getTitleText =()=>{
 switch (modalStatus){
  case 'idle': return t('idleStatusConfirmationTitle') || 'Confirmation' ;
  case 'executing': return t('processing') || 'Processing' ;
  case 'success': return t('successTitle') || 'Success' ;
  case 'error': return t('errorTitle') || 'Error';
  default:return '';
  }
 };

const renderStatusSuccessOrErrorContent =(statusType:ModalStatusType)=>{
 return(
  <>
   <h3 id={titleId} className="status-modal-title">
    {getTitleText()}
   </h3>
   <p id="status-modal-message" className="status-modal-message">
    {message}
   </p>
   {showCountdown && (
    <div className="auto-close-countdown">
     <p className="countdown-text">
      {t('autoCloseIn') || 'Close in'}
      <span className="countdown-number">
       {timeLeft}s
      </span>
     </p>
    </div>
   )}
   <button className={`status-modal-button close-button ${statusType}`}
    onClick={handleManualClose} aria-label={t('closeButton')}
    >
    {t('closeButton')} {showCountdown && `(${timeLeft}s)`}
   </button>
  </>
 )
}
const renderContent = ()=>{
 switch (modalStatus){
  case 'idle':
   return (
    <>
     <h3 id={titleId} className="status-modal-title">
      {getTitleText()}
     </h3>
     <p id="status-modal-message" className="status-modal-message">
      {message}
     </p>

     <div className="status-modal-actions">
      <button className="status-modal-button cancel-button"
       onClick={handleManualClose} aria-label={t('cancel')}>
        {t('cancel')}
      </button>

      <button className="status-modal-button confirm-button"
      onClick={handleConfirm}
      aria-label={t('proceedToDeletionButton')}
      >
       {t('proceedToDeletionButton')}
      </button>
     </div>
    </>
   );

   case 'executing':
    return(
     <>
      <h3 id={titleId} className="status-modal-title">
      {getTitleText()}
      </h3>
     <div className="loading-spinner"
      aria-hidden='true'
     ></div>

      <p id="status-modal-message" className="status-modal-message">{message}</p>
     </>
    );

    case 'success':
     case 'error':
     return (
      renderStatusSuccessOrErrorContent(modalStatus)
     );

     default:
      return null;
 }
}

 return (
/* No role here: RTAConfirmationModal wraps this and declares itself the dialog
   (alertdialog when it holds this component), and a screen reader cannot report
   a dialog nested in a dialog. */
<div className={containerClass}>
  {renderContent()}
</div>

  )
}

export default StatusModalUI